# Generated by Django 5.1.4 on 2025-04-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_athlete_slug_organization_slug_alter_athlete_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
